#!/usr/bin/env bash
# ============================================================================
# setup_cloudflare_tunnel.sh — one-time tunnel provisioning.
#
# Sets up a stable public URL that forwards to your local mlx_lm.server.
# Your deployed backend then sets LOCAL_LLM_BASE_URL to that URL and
# every LLM call hits the fine-tuned model running on your Mac.
#
# Two modes:
#   quick (default for testing): ephemeral trycloudflare.com URL, random
#         subdomain that changes per session, no Cloudflare account needed.
#         Useful for "does this work end-to-end?" but NOT for production
#         (the URL changes every time cloudflared restarts).
#
#   named (recommended for production): stable URL tied to a tunnel ID
#         you own. URL pattern is https://<UUID>.cfargotunnel.com — never
#         changes for the life of the tunnel. Requires a free Cloudflare
#         account.
#
# USAGE
#   bash backend/scripts/setup_cloudflare_tunnel.sh                # named (default)
#   bash backend/scripts/setup_cloudflare_tunnel.sh quick          # ephemeral test
#   bash backend/scripts/setup_cloudflare_tunnel.sh named --print-url   # show stable URL only
#
# WHAT THIS DOES IN NAMED MODE
#   1. brew install cloudflared (if missing)
#   2. cloudflared tunnel login (opens browser — one-time auth)
#   3. cloudflared tunnel create goal-planning-mlx (one-time, idempotent)
#   4. Writes ~/.cloudflared/config.yml routing the tunnel to 127.0.0.1:8080
#   5. Prints the stable URL you'll set as LOCAL_LLM_BASE_URL
#
# AFTER THIS RUNS
#   bash backend/scripts/install_launchd_jobs.sh
#     (the cloudflared launchd job uses this config and stays alive forever)
#
#   In your DEPLOYED backend's env (Vercel/Render/Railway/etc.):
#     LOCAL_LLM_BASE_URL=https://<UUID>.cfargotunnel.com/v1
#     LOCAL_LLM_MODEL=fused
#
#   (Optional) unset OPENAI_API_KEY in the deploy to force ALL traffic
#   to the fine-tune. Or leave both set — the local URL wins by design.
# ============================================================================

set -euo pipefail

MODE="${1:-named}"
PRINT_URL_ONLY=false
for arg in "${@:2}"; do
  case "$arg" in
    --print-url) PRINT_URL_ONLY=true ;;
    *) ;;
  esac
done

TUNNEL_NAME="goal-planning-mlx"
LOCAL_PORT="8080"
CONFIG_DIR="$HOME/.cloudflared"
CONFIG_FILE="$CONFIG_DIR/config.yml"

# ---- 1. Install cloudflared ----------------------------------------------
if ! command -v cloudflared >/dev/null 2>&1; then
  echo "Installing cloudflared via Homebrew..."
  if ! command -v brew >/dev/null 2>&1; then
    echo "✗ Homebrew not found. Install brew first: https://brew.sh" >&2
    exit 1
  fi
  brew install cloudflared
fi

case "$MODE" in
  quick)
    echo ""
    echo "=== QUICK MODE — ephemeral tunnel ==="
    echo "    The URL will be printed by cloudflared below. It changes every run."
    echo "    Ctrl+C to stop."
    echo ""
    exec cloudflared tunnel --url "http://127.0.0.1:$LOCAL_PORT"
    ;;

  named)
    # Continue below.
    ;;

  *)
    echo "✗ Unknown mode: $MODE (use 'quick' or 'named')" >&2
    exit 1
    ;;
esac

# ---- NAMED MODE ----------------------------------------------------------
mkdir -p "$CONFIG_DIR"

# ---- 2. Login (one-time, idempotent) -------------------------------------
# cloudflared writes ~/.cloudflared/cert.pem on success.
if [[ ! -f "$CONFIG_DIR/cert.pem" ]]; then
  echo ""
  echo "=== Cloudflare login ==="
  echo "    A browser will open. Sign in (or create a free account) and"
  echo "    pick ANY zone (you don't need to own a domain — the URL we use"
  echo "    is *.cfargotunnel.com, which Cloudflare gives you for free)."
  echo ""
  cloudflared tunnel login
fi

# ---- 3. Create the tunnel (idempotent) -----------------------------------
# `tunnel create` is NOT idempotent — it errors if the name already exists.
# So check first.
EXISTING_ID="$(cloudflared tunnel list 2>/dev/null | awk -v n="$TUNNEL_NAME" 'NR>1 && $2==n {print $1}')"

if [[ -z "$EXISTING_ID" ]]; then
  echo "Creating tunnel '$TUNNEL_NAME'..."
  cloudflared tunnel create "$TUNNEL_NAME"
  EXISTING_ID="$(cloudflared tunnel list 2>/dev/null | awk -v n="$TUNNEL_NAME" 'NR>1 && $2==n {print $1}')"
fi

if [[ -z "$EXISTING_ID" ]]; then
  echo "✗ Failed to create or find tunnel '$TUNNEL_NAME'. Run:" >&2
  echo "    cloudflared tunnel list" >&2
  echo "  to see what's there." >&2
  exit 1
fi

TUNNEL_ID="$EXISTING_ID"
STABLE_URL="https://$TUNNEL_ID.cfargotunnel.com"

if [[ "$PRINT_URL_ONLY" == "true" ]]; then
  echo "$STABLE_URL/v1"
  exit 0
fi

# ---- 4. Write the routing config -----------------------------------------
# This tells cloudflared which local port to forward traffic to.
# Credentials file is auto-named by `tunnel create` as <UUID>.json.
CREDENTIALS_FILE="$CONFIG_DIR/$TUNNEL_ID.json"

cat > "$CONFIG_FILE" <<EOF
# Auto-generated by backend/scripts/setup_cloudflare_tunnel.sh.
# Don't edit by hand — re-run the script if you need to change anything.
tunnel: $TUNNEL_ID
credentials-file: $CREDENTIALS_FILE

ingress:
  # Forward all traffic to the local mlx_lm.server. The server speaks
  # /v1/chat/completions plus a /health route. We accept any path.
  - service: http://127.0.0.1:$LOCAL_PORT

  # Required catch-all (cloudflared rejects configs without one).
  - service: http_status:404
EOF

echo "  ✓ wrote $CONFIG_FILE"

# ---- 5. Final summary ----------------------------------------------------
cat <<SUMMARY

============================================================
  Tunnel ready.
============================================================

  Tunnel name : $TUNNEL_NAME
  Tunnel ID   : $TUNNEL_ID
  Forwards    : 127.0.0.1:$LOCAL_PORT  →  $STABLE_URL
  Config file : $CONFIG_FILE
  Credentials : $CREDENTIALS_FILE

Next:
  1. Install the launchd jobs so the tunnel + model server start at login:
       bash backend/scripts/install_launchd_jobs.sh

  2. In your DEPLOYED backend (Vercel/Render/Railway/etc.) set these env vars:
       LOCAL_LLM_BASE_URL=$STABLE_URL/v1
       LOCAL_LLM_MODEL=fused

  3. (Optional) Test the tunnel from anywhere:
       curl -s $STABLE_URL/v1/models

============================================================
SUMMARY
