"""
Onboarding API Routes
Step 0: Questionnaire
"""

from fastapi import APIRouter, HTTPException, Depends
from pydantic import BaseModel
from typing import List, Optional
import httpx
import os
# Note: orchestrator will be injected via dependency injection

router = APIRouter()

SERVICE_HUB_URL = os.getenv("SERVICE_HUB_URL", "http://localhost:3001")

class OnboardingRequest(BaseModel):
    email: str
    demographics: Optional[dict] = None
    barrierTypes: List[str]
    motivationType: str
    goals: List[str]
    dreams: List[str]
    currentChallenges: List[str]

class OnboardingResponse(BaseModel):
    userId: str
    pathId: str
    message: str

@router.post("/", response_model=OnboardingResponse)
async def create_onboarding(request: OnboardingRequest):
    """
    Create user profile and generate initial path
    Also syncs to ServiceHub if serviceHubData is provided
    """
    try:
        # Create user profile
        user_profile = {
            "id": "",  # Will be generated by DB
            "demographics": request.demographics or {},
            "barrierTypes": request.barrierTypes,
            "motivationType": request.motivationType,
            "goals": request.goals,
            "dreams": request.dreams,
            "currentChallenges": request.currentChallenges
        }
        
        # In production: Use orchestrator via dependency injection
        # For now, return mock response
        response = OnboardingResponse(
            userId="user_123",
            pathId="path_123",
            message="Path generated successfully"
        )
        
        # Sync to ServiceHub if serviceHubData is provided (from frontend)
        # Note: This is handled by the frontend directly, but we could add it here too
        
        return response
    
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/questions")
async def get_onboarding_questions():
    """
    Get onboarding questionnaire
    """
    return {
        "questions": [
            {
                "id": "q1",
                "question": "What types of systematic barriers do you face?",
                "type": "multiple_choice",
                "options": [
                    "Autism",
                    "ADHD",
                    "OCD",
                    "Bipolar Disorder",
                    "Sensory Impairment",
                    "Physical Impairment",
                    "Visible Minority",
                    "Other"
                ]
            },
            {
                "id": "q2",
                "question": "What are your main goals?",
                "type": "text",
                "placeholder": "Describe your goals..."
            },
            {
                "id": "q3",
                "question": "What are your dreams?",
                "type": "text",
                "placeholder": "Describe your dreams..."
            },
            {
                "id": "q4",
                "question": "What are the main things stopping you from your dreams?",
                "type": "text",
                "placeholder": "Describe your challenges..."
            },
            {
                "id": "q5",
                "question": "What type of motivation works best for you?",
                "type": "single_choice",
                "options": [
                    "Intrinsic (internal drive)",
                    "Extrinsic (external rewards)",
                    "Achievement-based",
                    "Social connection",
                    "Fear-based",
                    "Reward-based"
                ]
            }
        ]
    }
