"""
Path API Routes
Step 1: Path View - Serves AI-generated paths from agent orchestration
"""

from fastapi import APIRouter, HTTPException
from typing import List

router = APIRouter()


@router.get("/{path_id}")
async def get_path(path_id: str):
    """
    Get a generated path by ID.
    First checks if it was generated by the agent system during onboarding.
    """
    # Check the in-memory store from onboarding agent orchestration
    from api.routes.onboarding import generated_paths

    if path_id in generated_paths:
        return generated_paths[path_id]

    # Fallback for legacy/mock paths
    return {
        "id": path_id,
        "userId": "unknown",
        "name": "My Personal Path",
        "description": "Path toward your goals",
        "races": [],
        "stats": [
            {"name": "Mentality", "value": 3, "maxValue": 100, "color": "green"},
            {"name": "Happiness", "value": 8, "maxValue": 100, "color": "green"},
        ],
        "motivationWheel": {
            "id": "wheel_1",
            "options": ["Focus", "Energy", "Confidence", "Growth", "Resilience", "Connection"],
            "currentMotivation": None,
        },
        "createdAt": None,
        "updatedAt": None,
    }


@router.post("/{path_id}/adapt")
async def adapt_path(path_id: str, reflection_data: dict):
    """
    Adapt a path based on user reflection — triggers Reflection + Adaptation agents.
    """
    from api.routes.onboarding import generated_paths
    from core.orchestrator import Orchestrator

    if path_id not in generated_paths:
        raise HTTPException(status_code=404, detail="Path not found")

    path_data = generated_paths[path_id]
    user_id = path_data.get("userId", "unknown")

    orchestrator = Orchestrator()
    await orchestrator.initialize()

    adaptation_result = await orchestrator.adapt_path(
        user_id=user_id,
        path_id=path_id,
        reflection_data=reflection_data
    )

    await orchestrator.cleanup()

    # Merge adaptation into stored path
    generated_paths[path_id].update(adaptation_result)

    return adaptation_result

@router.get("/milestones/{milestone_id}/common-mistakes")
async def milestone_common_mistakes(milestone_id: str):
    """Real, cross-user 'what not to do' list for one milestone stage.

    Aggregate only — an indicator name, a percentage, and how many
    reflections it's based on. No individual's data is identifiable from
    this, so unlike the user-path endpoints this stays open.

    Milestone ids are structural (milestone_g{goal}_{dim}_{i}), so this
    naturally pools real signal across every user whose Nth milestone in a
    dimension is this one — not a single person's history.
    """
    from core.learning import get_common_mistakes

    mistakes = await get_common_mistakes(milestone_id)
    return {"milestoneId": milestone_id, "mistakes": mistakes}
