"""Run all three synthetic-data checks and write a dated markdown report.

    python -m scripts.synthetic_validation.report
    python -m scripts.synthetic_validation.report --out path/to/report.md

Loads the cohorts once and passes the same records to every check, so the
three verdicts describe exactly the same data. Aggregates only: no ids, no
emails, and privacy_nn suppresses any profile held by fewer than five real
people.
"""
from __future__ import annotations

import argparse
import sys
from datetime import date
from pathlib import Path

from scripts.synthetic_validation import fidelity, privacy_nn, utility_tstr
from scripts.synthetic_validation.common import load_people, split


def verdict(passed) -> str:
    return "PASS" if passed else "FAIL" if passed is False else "UNDETERMINED"


def build(people) -> str:
    real, synth = split(people)
    results = [fidelity.run(people), utility_tstr.run(people), privacy_nn.run(people)]
    fid, util, priv = results

    out = [
        f"# Synthetic data validation — {date.today().isoformat()}",
        "",
        f"The {len(synth)} synthetic accounts (all created 2026-07-12) checked against the "
        f"{len(real)} real accounts, on the three tests the course framework sets out. "
        "Generated by `backend/scripts/synthetic_validation/`; re-run to refresh.",
        "",
        "| check | result |",
        "|---|---|",
    ]
    out += [f"| {r.name} | **{verdict(r.passed)}** — {r.headline.split(' — ', 1)[-1]} |" for r in results]
    out += ["", "## What the numbers imply", ""]

    if priv.passed and fid.passed is False and util.passed is False:
        out += [
            "Privacy passes and fidelity and utility both fail. That is the signature of data "
            "generated from hand-written option lists with no real input: it cannot leak anyone, "
            "and it cannot represent anyone either. The generator draws one or two of nine "
            "conditions and one of three age bands uniformly at random, so the synthetic cohort "
            "has the wrong age profile, a fraction of the conditions real people report, and no "
            "real co-occurrence structure -- retrieval over it does worse than guessing its most "
            "common conditions.",
            "",
            "As it stands the batch is not a stand-in for real users in any agent evaluation. "
            "Whether to regenerate it (for example, seeded from real aggregate distributions) or "
            "to exclude it from evaluation entirely is the open design choice on the deck; these "
            "numbers are the evidence for that decision, not the decision itself.",
        ]
    else:
        out += ["The three checks do not fall into a single simple pattern; see each section."]

    out += [
        "",
        "## Method notes",
        "",
        "- Both cohorts go through the shared condition taxonomy first, so spelling "
        "(`low_income` vs `Limited Income`) is never counted as a difference.",
        "- Fidelity pass/fail is a bootstrap test, not a chosen threshold: an attribute fails "
        "only if it differs from the real cohort by more than chance would at these sample sizes.",
        "- The TSTR pass line (80% of TRTR) is a common rule of thumb, stated so it can be argued "
        "with. At this cohort size even the real pool only modestly beats a popularity guess, so "
        "the reference itself is weak.",
        "- Privacy uses both how the data was made and how close it sits to real records; "
        "neither alone is conclusive.",
    ]
    for r in results:
        out += ["", f"## {r.name} — {verdict(r.passed)}", "", r.headline, ""] + r.lines
    return "\n".join(out) + "\n"


def main() -> int:
    ap = argparse.ArgumentParser()
    default = (Path(__file__).resolve().parents[3] / "docs/reports"
               / f"synthetic-validation-{date.today().isoformat()}.md")
    ap.add_argument("--out", default=str(default))
    args = ap.parse_args()
    text = build(load_people())
    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text(text)
    print(text)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
