'use client'

import { useState, useEffect } from 'react'
import { useRouter, useParams } from 'next/navigation'
import Link from 'next/link'
import { ArrowLeft, ExternalLink, BookOpen, Star, ChevronRight, Wrench, MessageSquare, Package, Lightbulb } from 'lucide-react'
import { useAgentPath } from '../../context/AgentPathContext'
import { resolveToolLink } from '@/lib/toolLink'
import CommonMistakes from '@/app/components/CommonMistakes'


interface Tool {
  id: string
  type: 'service' | 'commentary' | 'product' | 'other'
  name: string
  description: string
  url?: string
  rating?: number | null
  progress?: number // Progress percentage for this service (0-100)
  status?: 'not_started' | 'in_progress' | 'completed'
}

const toolIcons = {
  service: Wrench,
  commentary: MessageSquare,
  product: Package,
  other: Lightbulb
}

const toolColors = {
  service: 'bg-blue-50 border-blue-200 text-blue-700',
  commentary: 'bg-purple-50 border-purple-200 text-purple-700',
  product: 'bg-emerald-50 border-emerald-200 text-emerald-700',
  other: 'bg-amber-50 border-amber-200 text-amber-700'
}

export default function MilestoneDetailView() {
  const params = useParams()
  const router = useRouter()
  const milestoneId = params.id as string
  const { pathPlanning, toolRecommendation } = useAgentPath()
  const [milestone, setMilestone] = useState<any>(null)
  const [loading, setLoading] = useState(true)

  // Saved completion lives in race_progress (localStorage is only a cache).
  // Without this the page reported "in progress / 0%" for a milestone the user
  // had already ticked off on the trail.
  const [isComplete, setIsComplete] = useState(false)
  useEffect(() => {
    try {
      const s = localStorage.getItem('completedMilestoneIds')
      if (s) setIsComplete(new Set(JSON.parse(s)).has(milestoneId))
    } catch {}
    fetch('/api/me/progress', { credentials: 'include' })
      .then((r) => (r.ok ? r.json() : null))
      .then((d) => {
        if (!d) return
        const rows = d.progress || d.rows || d || []
        if (!Array.isArray(rows)) return
        setIsComplete(
          rows.some((r: any) => r.kind === 'completed' && r.milestone_id === milestoneId)
        )
      })
      .catch(() => {})
  }, [milestoneId])

  useEffect(() => {
    // Prefer the real milestone produced by the path-planning agent. Fall back
    // to the mock catalogue (legacy demo IDs like 'r1c1') and finally to a
    // generic stub so the page never crashes.
    const agentMilestone = (pathPlanning?.milestones || []).find(
      (m: any) => m.id === milestoneId
    )
    if (agentMilestone) {
      const recs: any[] = (toolRecommendation?.recommendations || {})[milestoneId] || []
      const agentTools = recs.map((t: any, idx: number) => ({
        id: t.id || `t${idx}`,
        type: (t.type === 'service' || t.type === 'commentary' || t.type === 'product') ? t.type : 'other',
        name: t.name || 'Recommended tool',
        description: t.description || '',
        url: t.url,
        rating: typeof t.rating === 'number' ? t.rating : null,
      }))
      const agentTasks: string[] = ((pathPlanning?.tasks || []) as any[])
        .filter((t) => t.milestoneId === milestoneId)
        .slice(0, 6)
        .map((t) => t.name || t.title)
      setMilestone({
        id: agentMilestone.id,
        name: agentMilestone.name || agentMilestone.title,
        description: agentMilestone.description || 'Personalised milestone generated by your agents.',
        status: isComplete ? 'completed' : (agentMilestone.status || 'in_progress'),
        progress: isComplete ? 100 : (agentMilestone.progress ?? 0),
        race: agentMilestone.race,
        nextSteps: agentTasks.length ? agentTasks : (agentMilestone.nextSteps || []),
        tools: agentTools,
      })
    } else {
      // No demo catalogue — an unresolved milestone shows a minimal real stub
      // (no fake tools) rather than mock content.
      setMilestone({
        id: milestoneId,
        name: `Milestone: ${milestoneId}`,
        description: 'This milestone is part of your personalized path.',
        status: 'pending',
        tools: [],
      })
    }
    setLoading(false)
  }, [milestoneId, pathPlanning, toolRecommendation, isComplete])

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-white/30 backdrop-blur-sm">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-cyan-600 mx-auto mb-4"></div>
          <p className="text-slate-600">Loading milestone...</p>
        </div>
      </div>
    )
  }

  if (!milestone) {
    return (
      <div className="flex items-center justify-center min-h-screen bg-white/30 backdrop-blur-sm">
        <div className="text-center">
          <p className="text-slate-600 mb-4">Milestone not found</p>
          <Link href="/races" className="text-cyan-600 hover:underline">Back to Races</Link>
        </div>
      </div>
    )
  }

  const toolsByType = {
    services: milestone.tools?.filter((t: Tool) => t.type === 'service') || [],
    commentaries: milestone.tools?.filter((t: Tool) => t.type === 'commentary') || [],
    products: milestone.tools?.filter((t: Tool) => t.type === 'product') || [],
    other: milestone.tools?.filter((t: Tool) => t.type === 'other') || []
  }

  return (
    <div className="min-h-screen bg-white/20 backdrop-blur-sm p-4 md:p-8 relative overflow-hidden">
      {/* Background decorations */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none pref-gamify">
        <div className="absolute top-20 left-10 w-72 h-72 bg-cyan-500/20 rounded-full blur-3xl animate-pulse" style={{ animationDuration: '4s' }} />
        <div className="absolute bottom-20 right-10 w-96 h-96 bg-purple-500/20 rounded-full blur-3xl animate-pulse" style={{ animationDuration: '5s', animationDelay: '1s' }} />
        <div className="absolute top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[600px] h-[600px] bg-pink-500/15 rounded-full blur-3xl animate-pulse" style={{ animationDuration: '6s', animationDelay: '2s' }} />
      </div>
      <div className="relative z-10">
      <div className="max-w-4xl mx-auto">
        {/* Back Link */}
        <Link
          href="/races"
          className="inline-flex items-center text-slate-600 hover:text-slate-900 font-medium mb-6 group"
        >
          <ArrowLeft className="mr-2 h-5 w-5 group-hover:-translate-x-1 transition-transform" />
          Back to Races
        </Link>

        {/* Milestone Header Card */}
        <div className="bg-white rounded-2xl border-2 border-slate-200 p-6 md:p-8 mb-6 shadow-sm">
          <div className="flex flex-col md:flex-row md:items-start md:justify-between gap-4">
            <div className="flex-1">
              <div className="flex items-center gap-3 mb-2">
                {milestone.race && (
                  <span className="text-sm px-3 py-1 bg-slate-100 rounded-full text-slate-600">
                    {milestone.race}
                  </span>
                )}
              </div>
              <h1 className="text-2xl md:text-3xl font-bold text-slate-900 mb-3">{milestone.name}</h1>
              <p className="text-slate-600">{milestone.description}</p>
            </div>

            {/* Stats for recommended choices */}
            {milestone.successRate && (
              <div className="bg-emerald-50 rounded-xl p-4 text-center min-w-[140px]">
                <div className="text-3xl font-bold text-emerald-600">{milestone.successRate}%</div>
                <div className="text-sm text-emerald-700">Success Rate</div>
                <div className="text-xs text-slate-500 mt-1">{milestone.attempts?.toLocaleString()} attempts</div>
              </div>
            )}
          </div>

          {/* Progress bar for current milestone */}
          {milestone.progress !== undefined && (
            <div className="mt-6">
              <div className="flex justify-between text-sm mb-2">
                <span className="text-slate-600">Progress</span>
                <span className="font-bold text-slate-900">{milestone.progress}%</span>
              </div>
              <div className="h-3 bg-slate-100 rounded-full overflow-hidden">
                <div 
                  className="h-full bg-gradient-to-r from-cyan-500 to-blue-500 rounded-full transition-all"
                  style={{ width: `${milestone.progress}%` }}
                />
              </div>
            </div>
          )}

          {/* Next Steps */}
          {milestone.nextSteps && (
            <div className="mt-6 pt-6 border-t border-slate-200">
              <h3 className="font-semibold text-slate-900 mb-3">Next Steps:</h3>
              <div className="space-y-2">
                {milestone.nextSteps.map((step: string, idx: number) => (
                  <div key={idx} className="flex items-center gap-3">
                    <div className={`w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold ${
                      idx === 0 ? 'bg-amber-400 text-white' : 'bg-slate-200 text-slate-600'
                    }`}>
                      {idx + 1}
                    </div>
                    <span className={idx === 0 ? 'font-medium' : 'text-slate-600'}>{step}</span>
                  </div>
                ))}
              </div>
              <div className="mt-3 flex items-start gap-2 p-3 bg-sky-50 border border-sky-200 rounded-xl">
                <span className="text-base mt-0.5">📅</span>
                <p className="text-sm text-sky-800">
                  These have been added to your <Link href="/calendar" className="font-bold underline hover:text-sky-600">Calendar</Link>, and can be seen by clicking the Calendar View below!
                </p>
              </div>
            </div>
          )}

          <CommonMistakes milestoneId={milestone.id} />
        </div>

        {/* Tools Section */}
        <div className="bg-white rounded-2xl border-2 border-slate-200 p-6 md:p-8 shadow-sm">
          <h2 className="text-xl font-bold text-slate-900 mb-6">Recommended Tools</h2>

          {/* Barriers Unlocked */}
          {(milestone.tools?.length > 0) && (
            <div className="mb-6 p-4 bg-violet-50 border-2 border-violet-200 rounded-xl">
              <div className="flex items-center gap-2 mb-3">
                <span className="text-lg">🛡️</span>
                <h3 className="text-lg font-semibold text-violet-900">Barriers Unlocked</h3>
              </div>
              <p className="text-sm text-violet-700 mb-3">Each tool below addresses specific barriers. Complete them to unlock progress.</p>
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-violet-200">
                      <th className="text-left py-2 pr-4 text-violet-800 font-bold">Tool</th>
                      <th className="text-left py-2 pr-4 text-violet-800 font-bold">Type</th>
                      <th className="text-left py-2 text-violet-800 font-bold">Barriers Unlocked</th>
                    </tr>
                  </thead>
                  <tbody>
                    {milestone.tools.map((tool: Tool) => (
                      <tr key={tool.id} className="border-b border-violet-100 last:border-0">
                        <td className="py-2 pr-4">
                          <div className="flex items-center gap-2">
                            {(() => { const TI = toolIcons[tool.type] || Lightbulb; return <TI className="w-4 h-4 text-violet-500 flex-shrink-0" /> })()}
                            <span className="font-medium text-slate-800">{tool.name}</span>
                          </div>
                        </td>
                        <td className="py-2 pr-4 capitalize text-slate-500">{tool.type}</td>
                        <td className="py-2">
                          <div className="flex flex-wrap gap-1">
                            {(tool.type === 'service' ? ['Access', 'Support'] : tool.type === 'product' ? ['Focus', 'Routine'] : tool.type === 'commentary' ? ['Knowledge', 'Confidence'] : ['Community', 'Connection']).map(b => (
                              <span key={b} className="text-[10px] px-2 py-0.5 rounded-full bg-violet-100 text-violet-700 font-medium">{b}</span>
                            ))}
                          </div>
                        </td>
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
              <p className="text-xs text-violet-500 mt-2 italic">Could add gifts of barriers fully unlocked</p>
            </div>
          )}

          {/* Services */}
          {toolsByType.services.length > 0 && (
            <ToolSection 
              title="Services" 
              icon={Wrench}
              tools={toolsByType.services} 
              colorClass="bg-blue-50 border-blue-200"
            />
          )}

          {/* Commentaries */}
          {toolsByType.commentaries.length > 0 && (
            <ToolSection 
              title="Commentaries / Reviews / Videos / Articles" 
              icon={MessageSquare}
              tools={toolsByType.commentaries} 
              colorClass="bg-purple-50 border-purple-200"
            />
          )}

          {/* Products */}
          {toolsByType.products.length > 0 && (
            <ToolSection 
              title="Products" 
              icon={Package}
              tools={toolsByType.products} 
              colorClass="bg-emerald-50 border-emerald-200"
            />
          )}

          {/* Other Tools */}
          {toolsByType.other.length > 0 && (
            <ToolSection 
              title="Other Helpful Tools" 
              icon={Lightbulb}
              tools={toolsByType.other} 
              colorClass="bg-amber-50 border-amber-200"
            />
          )}

          {milestone.tools?.length === 0 && (
            <div className="text-center py-8 text-slate-500">
              <p>No tools recommended for this milestone yet.</p>
              <Link href="/pit-stop" className="text-cyan-600 hover:underline mt-2 inline-block">
                Browse all tools in Pit Stop →
              </Link>
            </div>
          )}

          {/* Actions */}
          <div className="mt-8 pt-6 border-t border-slate-200 flex flex-wrap gap-4">
            <Link
              href={`/reflection?contextType=milestone&contextId=${milestoneId}`}
              className="inline-flex items-center gap-2 bg-slate-900 text-white px-6 py-3 rounded-xl hover:bg-slate-800 transition-colors font-medium"
            >
              <BookOpen className="h-5 w-5" />
              Journal / Reflection
            </Link>
            <Link
              href="/calendar"
              className="inline-flex items-center gap-2 bg-slate-100 text-slate-700 px-6 py-3 rounded-xl hover:bg-slate-200 transition-colors font-medium"
            >
              Calendar View
              <ChevronRight className="h-5 w-5" />
            </Link>
            <Link
              href="/pit-stop"
              className="inline-flex items-center gap-2 bg-cyan-50 text-cyan-700 px-6 py-3 rounded-xl hover:bg-cyan-100 transition-colors font-medium"
            >
              <Wrench className="h-5 w-5" />
              Pit Stop
            </Link>
          </div>
        </div>
      </div>
      </div>
    </div>
  )
}
function ToolSection({ title, icon: Icon, tools, colorClass }: { 
  title: string
  icon: any
  tools: Tool[]
  colorClass: string 
}) {
  const getStatusColor = (status?: string) => {
    switch (status) {
      case 'completed': return 'bg-green-500'
      case 'in_progress': return 'bg-blue-500'
      default: return 'bg-gray-300'
    }
  }

  const getStatusText = (status?: string) => {
    switch (status) {
      case 'completed': return 'Completed'
      case 'in_progress': return 'In Progress'
      default: return 'Not Started'
    }
  }

  return (
    <div className="mb-6">
      <div className="flex items-center gap-2 mb-3">
        <Icon className="w-5 h-5 text-slate-600" />
        <h3 className="text-lg font-semibold text-slate-900">{title}</h3>
      </div>
      <div className="space-y-3">
        {tools.map((tool) => {
          const progress = tool.progress || 0
          const status = tool.status || 'not_started'
          
          return (
            <div 
              key={tool.id} 
              className={`border-2 rounded-xl p-4 hover:shadow-md transition-all ${colorClass}`}
            >
              <div className="flex justify-between items-start mb-3">
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <h4 className="font-semibold text-slate-900">{tool.name}</h4>
                    {status !== 'not_started' && (
                      <span className={`px-2 py-0.5 rounded-full text-xs font-medium ${
                        status === 'completed' 
                          ? 'bg-green-100 text-green-700' 
                          : 'bg-blue-100 text-blue-700'
                      }`}>
                        {getStatusText(status)}
                      </span>
                    )}
                  </div>
                  <p className="text-sm text-slate-600 mb-2">{tool.description}</p>
                  {tool.rating && (
                    <div className="flex items-center gap-1">
                      <Star className="w-4 h-4 text-amber-400 fill-amber-400" />
                      <span className="text-sm font-medium text-slate-700">{tool.rating}/5</span>
                    </div>
                  )}
                </div>
                <a
                  href={resolveToolLink(tool.url, tool.name).href}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="ml-4 p-2 text-slate-600 hover:text-cyan-600 hover:bg-white rounded-lg transition-colors"
                >
                  <ExternalLink className="h-5 w-5" />
                </a>
              </div>
              
              {/* Progress Bar for Services */}
              {tool.type === 'service' && (
                <div className="mt-3 pt-3 border-t border-slate-200">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs font-medium text-slate-600">Progress</span>
                    <span className="text-xs font-bold text-slate-700">{progress}%</span>
                  </div>
                  <div className="w-full h-2 bg-slate-200 rounded-full overflow-hidden">
                    <div 
                      className={`h-full transition-all duration-300 ${getStatusColor(status)}`}
                      style={{ width: `${progress}%` }}
                    />
                  </div>
                  {progress > 0 && progress < 100 && (
                    <p className="text-xs text-slate-500 mt-1">
                      {progress < 50 ? 'Getting started...' : progress < 90 ? 'Making good progress!' : 'Almost there!'}
                    </p>
                  )}
                </div>
              )}
            </div>
          )
        })}
      </div>
    </div>
  )
}

